workspace:
  base: /react
  path: drone/dinbandang

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  node:
    image: node:8.9.1
    pull: true
    commands:
      - npm install
      - npm run build