workspace:
  base: /react
  path: drone/dinbandang

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  node:
    image: node:8.9.1
    pull: true
    commands:
      - npm install
      - npm run build

  scp:
    image: appleboy/drone-scp
    host:
      - 139.162.9.68
    username: root
    secrets: [ ssh_password ]
    target: /var/www/html/dinbandan
    source:
      - ./build/static
      - ./build/index.html
      - ./biuld/favicon.ico
    when:
      branch: master
      status: [success]

  ssh:
    image: appleboy/drone-ssh
    host:
      - 139.162.9.68
    username: root
    secrets: [ ssh_password ]
    script:
      - rm -rf /var/www/html/index.html
      - rm -rf /var/www/html/static
      - mv /var/www/html/dinbandan/build/* /var/www/html/dinbandan/
      - rmdir /var/www/html/dinbandan/build